Output esm, cjs, and umd packages
ckeditor/ckeditor4-integrations-common pull request #18
Opened 2021-05-12 14:56 UTC by MMMalik

### Changes

- replaced `webpack` with `rollup`
- configured `rollup` so that 3 packages are created: `cjs`, `esm`, `umd`
- copied script from seemingly abandoned `load-script` package to a local file
- updated `package.json` with `main` and `module` fields, removed `load-script` from dependencies

### Gains

See table below (`polyfills` means IE11 and node 10 stuff).

| Package | Current size | After changes |
| --- | --- | --- |
| ckeditor4-react | v1 (polyfills included): **51.7 KB**<br> v2 (umd, no polyfills): **31.1 KB** | v1 (polyfills included): **39.9 KB**<br> v2 (umd, no polyfills): **11.3 KB** |
| ckeditor4-angular | sample `ng` app (no polyfills): **167.3 KB** | sample `ng` app (no polyfills): **147.3 KB** |
| ckeditor4-vue | ckeditor (no polyfills): **24.2 KB**<br> legacy(polyfills included): 35.7 KB | ckeditor: **4.1 KB**, legacy: **27 KB** |  

* There is around ~20 KB gain if no polyfills are included.
* There is around ~10 KB gain if polyfills are provided by integration

### Considerations

I believe this is a BREAKING CHANGE. I suggest to release these changes as `1.0.0`. All integration packages will require small adjustments. All packages depending on our integrations _might_ need adjustments due to missing polyfills. 

### To test

2021-06-07 10:39 UTC, Comandeer requested changes
Overally looks good, there are some minor issues.

2021-06-07 10:39 UTC, Comandeer commented on package.json
> +		"webpack": "^4.44.2"
Shouldn't it be removed? :thinking:

2021-06-07 10:39 UTC, Comandeer commented on rollup.config.js
> +*/`;
```suggestion
 * @license Copyright (c) 2003-2021, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md.
 */`;
```

2021-06-07 10:39 UTC, Comandeer commented on src/loadScript.js
> +module.exports = function load( src, opts, cb ) {
I'd change it to ESM as it's the only source file now that still uses CJS. And, if I'm not mistaken, this rewrite would also allow us to drop `@rollup/plugin-commonjs`.

2021-06-16 07:08 UTC, MMMalik commented on package.json
> +		"webpack": "^4.44.2"
Webpack is still used in `karma.conf.js`. It should be replaced with Rollup but I didn't want to extend the scope of this task. Would you agree to create a follow-up task for that?

2021-06-16 07:13 UTC, MMMalik commented on src/loadScript.js
> +module.exports = function load( src, opts, cb ) {
That's a good idea. I'll give it a try.

2021-06-16 07:34 UTC, MMMalik commented
Thanks @Comandeer. As per your suggestion `loadScript` was transformed from CommonJS into ESM. `@rollup/plugin-commonjs` was removed.

2021-06-16 11:34 UTC, Comandeer commented on package.json
> +		"webpack": "^4.44.2"
Yes, it sounds like a good candidate for a follow-up task.

2021-06-16 15:12 UTC, Comandeer approved these changes
LGTM! 🎉 
Tested with https://github.com/MMMalik/ckeditor4-integrations-common-t-17/tree/52b4f73b655edebcfc30d8639f98633214997fe9 and https://github.com/Comandeer/ckeditor4-angular-t-191/tree/b2be9d3c3054eed10c73694cd833e7c51a2e9d97.

2021-06-16 15:16 UTC, merged