Bump dependencies
ckeditor/ckeditor4-integrations-common pull request #24
Opened 2022-05-06 07:01 UTC by sculpt0r

2022-05-30 13:25 UTC, KarolDawidziuk requested changes
Hiello @sculpt0r and sorry for waiting so long for this review. 🙏 

Overall, everything looks good but since this PR was created some of the libraries have been updated. 
Please see my inline comments.

Also, let's add the same version of node(12) to the `nvmrc` file as used in `Travis`.

2022-05-30 13:25 UTC, KarolDawidziuk commented on package.json
> +		"@babel/core": "^7.17.10",
```suggestion
		"@babel/core": "^7.18.2",
```
There is a newer version of `babel/core`

2022-05-30 13:25 UTC, KarolDawidziuk commented on package.json
> +		"eslint": "^8.14.0",
```suggestion
		"eslint": "^8.16.0",
```
There is a newer version of `eslint`.

2022-05-30 13:25 UTC, KarolDawidziuk commented on package.json
> +		"karma": "^6.3.19",
```suggestion
		"karma": "^6.3.2",
```
There is a newer version of `karma`.

2022-05-30 13:25 UTC, KarolDawidziuk commented on package.json
> +		"rollup": "^2.72.0",
```suggestion
		"rollup": "^2.75.3",
```

There is a newer version of `rollup`.

2022-06-03 04:59 UTC, sculpt0r commented
@KarolDawidziuk - ready for another review :) All last-mentioned deps are bumped.

2022-06-03 05:02 UTC, sculpt0r commented
Forgot to change `.nvmrc`: so now it uses version `12` - the same travis does.

2022-06-06 05:48 UTC, KarolDawidziuk approved these changes
Thank you @sculpt0r for the updates.

LGTM! 🎉 
I just update `eslint` because two days ago there was a new version.

2022-06-06 06:15 UTC, merged